# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc6784adbd924590109c153c5465f451dd48be1127c3201057c305d258285490756c769555c9438fe1e468a4e7e946b421b1bcb3dad70911f6e7b2743d4b8ba5

test:
  secret_key_base: c5d4fc1fa6139eed8f9fa1cf2947d2f0e67c0d9cdb1119ddba8e5f625e72d2273b910ace81c7bb77472b28c20a992cc9927f12c4010d43f40552bdc9213d8626

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
